version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-dependencies:
        dependency-type: development
      peer-dependencies:
        dependency-type: production
    ignore:
      - dependency-name: fastify
        update-types: ['version-update:semver-major']
      - dependency-name: zod
        update-types: ['version-update:semver-major']
